### PR TITLE
Realign J3 and J2. Reroute D- around J4 and update ground fill

### PR DESCRIPTION
**Pull request by coliss86**
Align J3 & J2
image

D- around J4
image

### CODE REVIEW

**Comment by louckousse** [comment]
For a better accessibility to the breakout pins it could be interesting to align them at the top of the pcbs (just under the leds tracks). What do you think about it?

**Comment by coliss86** [comment]
Yep, you are right, I'll try to move them up asap.

**Comment by coliss86** [comment]
Like this ?
image

**Comment by louckousse** [comment]
I thought about something like that after all. 
image

**Comment by coliss86** [comment]
Perfect !

**Comment by louckousse** [comment]
Ok, I update the master.

**Pull request merged**
