### PR TITLE
Add USB Breakout

### PR DESCRIPTION
**Pull request by coliss86**

### CODE REVIEW

**Comment by coliss86** [comment]
I'm trying to add some hole on D+ D-, VCC and GND around the USB-C connector.

Here is the PCB before : 
image

And here is after : 
image
I moved U2, F1, R5 to create some space on the left of the connector. I also moved SW1 up (I think it is to closed to MX8)

But : 
 * there is a an routed path : between D- and GND o_O
* I don't managed to add a simple hole where I want, should I modify the electronic shema ? 

please help @louckousse  :)

**Comment by louckousse** [comment]
Hi @coliss86, you can either add multiple single pad from the keebio parts (in the pcb directly) or go fancy and add a molex for a real daughterboard (first in the schema file).

To add the single pad in pcbnew you hit O and then click where you want.

I'll look into the D- and GND link.

**Comment by louckousse** [comment]
image
That's why, when recreating route you need to refresh (or recreate) the fill zone.

**Comment by coliss86** [comment]
Progress : 
header added to schematic
image

Routing almost done (Ground pin of R5 is not connected) : 
image

header added to the PCB (wrong side and male but wanted I just want simple hole)
image

Fill zone refreshed

**Comment by coliss86** [comment]
Done !
image

**Comment by louckousse** [comment]
usb-breakout added on another pr

**Pull request closed without merging**
